### ISSUE TITLE
ClientProtocolException: StatusCode: 503

### ISSUE THREAD

**Issue by Merdica** [gggard/AndroidCaldavSyncAdapater#145]
```
11-26 13:09:49.161   29561-2124/? E/CaldavFacade﹕ Force get calendars from 'https://......' failed org.apache.http.client.ClientProtocolException: StatusCode: 503
11-26 13:10:20.014   29561-2124/? E/SyncAdapter﹕ IOException
    org.apache.http.client.ClientProtocolException: StatusCode: 503
            at org.gege.caldavsyncadapter.caldav.CaldavFacade.checkStatus(CaldavFacade.java:597)
            at org.gege.caldavsyncadapter.caldav.CaldavFacade.getUserPrincipal(CaldavFacade.java:330)
            at org.gege.caldavsyncadapter.caldav.CaldavFacade.getCalendarList(CaldavFacade.java:441)
            at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.onPerformSync(SyncAdapter.java:151)
            at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)
```

Device: Nexus 4 with 4.4
CalDAV Sync Adapter Version 1.8

**Comment by timoberger** [comment]
is this a permanent error?
how do i reproduce this error?
what happend next?
what is used on server side?
how is your account setup?

**Comment by Merdica** [comment]
Unfortunately I can't reproduce it right now. Instead I get the error I described in Issue #146.
I can't say what is used on server side. I have added only the url.

**Comment by Merdica** [comment]
Today I got the error again.
Before was a calendar on server side deleted.
Then it throws the same error.

I don't know what is used on server side.
