### ISSUE TITLE
Caldav sync error (general)

### ISSUE THREAD

**Issue by MegaMike48** [gggard/AndroidCaldavSyncAdapater#167]
Got this error above.
SW-version: Lastest (1.8.1)

Device: HTC-Sensation (Pyramid)
Android Version 4.0.3 / HTC-Sense: 3.6 / HTC-SW # 3.33.401.53

This 1.8.1 works perfect on an Samsung S4, but at the HTC
i´ve always this error...

MegaMike48

**Comment by dradux** [comment]
I receive this error as well.

One additional bit of information, I'm not sure about @MegaMike48, but I am hitting an owncloud caldav server over HTTPS, the SSL certificate is a self-signed cert.

It would be nice if we could get more details regarding the sync error...

**Comment by MegaMike48** [comment]
@dradux:

I use only HTTP to connect to "Baikal" on an RaspberryPi (via Apache2).

Do you need more informationas from me?

**Comment by t2000** [comment]
I did a logcat on a HTC Evo 3D, also with Stock Android 4.0.3 and Sense 3.6

This is the exception that occurs, can someone please have a look at it?

E/DatabaseUtils( 1001): Writing exception to parcel
E/DatabaseUtils( 1001): java.lang.NullPointerException
E/DatabaseUtils( 1001):         at android.database.MatrixCursor.<init>(MatrixCursor.java:42)
E/DatabaseUtils( 1001):         at android.database.MatrixCursor.<init>(MatrixCursor.java:58)
E/DatabaseUtils( 1001):         at com.android.providers.calendar.HtcFilterImpl_google.do_Query_REMINDERS(HtcFilterImpl_google.java:314)
E/DatabaseUtils( 1001):         at com.android.providers.calendar.HtcFilterImpl_google.handle_Query(HtcFilterImpl_google.java:64)
E/DatabaseUtils( 1001):         at com.android.providers.calendar.HtcCalendarProvider.query(HtcCalendarProvider.java:117)
E/DatabaseUtils( 1001):         at android.content.ContentProvider$Transport.query(ContentProvider.java:189)
E/DatabaseUtils( 1001):         at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:141)
E/DatabaseUtils( 1001):         at android.os.Binder.execTransact(Binder.java:338)
E/DatabaseUtils( 1001):         at dalvik.system.NativeStart.run(Native Method)
E/SyncAdapter( 6663): Updating calendar exception java.lang.NullPointerException
E/SyncAdapter( 6663): java.lang.NullPointerException
E/SyncAdapter( 6663):   at android.os.Parcel.readException(Parcel.java:1338)
E/SyncAdapter( 6663):   at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:182)
E/SyncAdapter( 6663):   at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:136)
E/SyncAdapter( 6663):   at android.content.ContentProviderProxy.query(ContentProviderNative.java:406)
E/SyncAdapter( 6663):   at android.content.ContentProviderClient.query(ContentProviderClient.java:50)
E/SyncAdapter( 6663):   at org.gege.caldavsyncadapter.caldav.entities.CalendarEvent.getAndroidEvent(CalendarEvent.java:882)
E/SyncAdapter( 6663):   at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.synchroniseEvents(SyncAdapter.java:324)
E/SyncAdapter( 6663):   at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.onPerformSync(SyncAdapter.java:170)
E/SyncAdapter( 6663):   at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:247)

**Comment by func0der** [comment]
Do you have Cyanogenmod or something similiar installed?
Privacy Guard can block the permissions and make the app failed like stated above.
The description of https://github.com/rfc2822/davdroid helped me to fix this problem.

**Comment by Frodox** [comment]
I have same issue after importing a _.vcs_ file, and trying to sync it.
Server: ownCloud, trying to import over HTTP. Android 4.3

**Comment by func0der** [comment]
I know this is just a workaround, but: Try to import to Owncloud, delete all contacts and the owncloud account from your phone and import them from owncloud after re-adding the owncloud account from the cloud to your phone.
