### ISSUE TITLE
javax.net.ssl.SSLException: SSL handshake aborted: ssl=0x75057768: I/O error during system call, Connection reset by peer

### ISSUE THREAD

**Issue by Merdica** [gggard/AndroidCaldavSyncAdapater#198]
```
05-09 11:15:39.320   6888-20073/? D/CaldavFacade﹕ LastAuthState: restored with user ***
05-09 11:15:39.320   6888-20073/? D/CaldavFacade﹕ LastAuthScope: restored
05-09 11:15:43.220   6888-20073/? D/CalendarEvent﹕ Creating calendar event for content://com.android.calendar/events/15037?caller_is_syncadapter=true&account_name=***&account_type=org.gege.caldavsyncadapter.account
05-09 11:16:00.150      598-615/? D/SyncManager﹕ failed sync operation *** u0 (org.gege.caldavsyncadapter.account), com.android.calendar, SERVER, latestRunTime 39977182, reason: 10007, SyncResult: syncAlreadyInProgress: true stats []
05-09 11:16:00.200      598-615/? D/SyncManager﹕ failed sync operation *** u0 (org.gege.caldavsyncadapter.account), com.android.calendar, LOCAL, latestRunTime 39977219, reason: 10007, SyncResult: syncAlreadyInProgress: true stats []
05-09 11:16:00.270      598-615/? D/SyncManager﹕ failed sync operation *** u0 (org.gege.caldavsyncadapter.account), com.android.calendar, LOCAL, latestRunTime 39977262, reason: 10007, SyncResult: syncAlreadyInProgress: true stats []
05-09 11:16:00.400      598-615/? D/SyncManager﹕ failed sync operation **** u0 (org.gege.caldavsyncadapter.account), com.android.calendar, LOCAL, latestRunTime 39977295, reason: 10007, SyncResult: syncAlreadyInProgress: true stats []
05-09 11:16:00.460      598-615/? D/SyncManager﹕ failed sync operation *** u0 (org.gege.caldavsyncadapter.account), com.android.calendar, LOCAL, latestRunTime 39977321, reason: 10007, SyncResult: syncAlreadyInProgress: true stats []
05-09 11:16:00.480      598-615/? D/SyncManager﹕ failed sync operation *** u0 (org.gege.caldavsyncadapter.account), com.android.calendar, LOCAL, latestRunTime 39977354, reason: 10007, SyncResult: syncAlreadyInProgress: true stats []
05-09 11:16:03.000   6888-20073/? E/SyncAdapter﹕ IOException
    javax.net.ssl.SSLException: SSL handshake aborted: ssl=0x75057768: I/O error during system call, Connection reset by peer
            at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
            at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:405)
            at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.<init>(OpenSSLSocketImpl.java:661)
            at com.android.org.conscrypt.OpenSSLSocketImpl.getInputStream(OpenSSLSocketImpl.java:632)
            at org.apache.http.impl.io.SocketInputBuffer.<init>(SocketInputBuffer.java:70)
            at org.apache.http.impl.SocketHttpClientConnection.createSessionInputBuffer(SocketHttpClientConnection.java:83)
            at org.apache.http.impl.conn.DefaultClientConnection.createSessionInputBuffer(DefaultClientConnection.java:170)
            at org.apache.http.impl.SocketHttpClientConnection.bind(SocketHttpClientConnection.java:106)
            at org.apache.http.impl.conn.DefaultClientConnection.openCompleted(DefaultClientConnection.java:129)
            at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:172)
            at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
            at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
            at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
            at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:509)
            at org.gege.caldavsyncadapter.caldav.CaldavFacade.getEvent(CaldavFacade.java:719)
            at org.gege.caldavsyncadapter.caldav.entities.CalendarEvent.fetchBody(CalendarEvent.java:264)
            at org.gege.caldavsyncadapter.caldav.entities.CalendarEvent.createAndroidEvent(CalendarEvent.java:906)
            at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.synchroniseEvents(SyncAdapter.java:330)
            at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.onPerformSync(SyncAdapter.java:170)
            at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)
```

**Comment by svrnwnsch** [comment]
Android is showing me the same error: SSL Handshake aborted: ssl=0x...

**Comment by Haoxiqiang** [comment]
maybe you can see these:
http://stackoverflow.com/questions/12885247/why-is-httpurlconnection-throwing-an-sslexception-while-on-a-mobile-data-connect
http://stackoverflow.com/questions/20741405/javax-net-ssl-sslexception-ssl-handshake-aborted-connection-reset-by-peer-while

**Comment by DevendraVaja** [comment]
Read this for the complete explanation and possible resolution: http://stackoverflow.com/questions/30538640/javax-net-ssl-sslexception-read-error-ssl-0x9524b800-i-o-error-during-system?lq=1
