### ISSUE TITLE
Bad URL formating

### ISSUE THREAD

**Issue by gggard** [gggard/AndroidCaldavSyncAdapater#3]
From Google Play :

java.lang.RuntimeException: java.net.MalformedURLException: Unknown protocol: xxxxx.yyyyyy.zzzzz
at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.onPerformSync(SyncAdapter.java:123)
at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:254)
Caused by: java.net.MalformedURLException: Unknown protocol: gastundgut-ney.synology.me
at java.net.URL.<init>(URL.java:184)
at java.net.URL.<init>(URL.java:127)
at org.gege.caldavsyncadapter.caldav.CaldavFacade.<init>(CaldavFacade.java:89)
at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.onPerformSync(SyncAdapter.java:98)
... 1 more

**Comment by gggard** [comment]
This is due to a wrong user input, inform user about the expected format of the URL (here they forget the http://)
