### ISSUE TITLE
NPE in SyncAdapter.createAndroidEvent

### ISSUE THREAD

**Issue by gggard** [gggard/AndroidCaldavSyncAdapater#41]
From Google play :

java.lang.RuntimeException: java.lang.NullPointerException
at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.onPerformSync(SyncAdapter.java:149)
at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:254)
Caused by: java.lang.NullPointerException
at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.createAndroidEvent(SyncAdapter.java:312)
at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.synchroniseEvents(SyncAdapter.java:173)
at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.onPerformSync(SyncAdapter.java:136)
... 1 more

**Comment by ancow** [comment]
I keep getting this reproducibly since I shortened a multi-day all-day event in the ownCloud web interface. If you need more information, I should be able to supply it.

**Comment by timoberger** [comment]
is this issue valid for the latest unofficial release?
https://github.com/timoberger/AndroidCaldavSyncAdapater/releases/tag/V1.8-alpha-2
feel free to reopen when needed

**Comment by ancow** [comment]
I had since uninstalled the app, so the original crash is gone.
A quick test suggests that the bug is fixed with the unofficial 1.8-alpha-2.
