### ISSUE TITLE
CaldavProtocolException in SyncAdapter.onPerformSync

### ISSUE THREAD

**Issue by gggard** [gggard/AndroidCaldavSyncAdapater#43]
From google play : 

java.lang.RuntimeException: org.gege.caldavsyncadapter.caldav.CaldavProtocolException: At line 254, column 50: mismatched tag
at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.onPerformSync(SyncAdapter.java:149)
at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:247)
Caused by: org.gege.caldavsyncadapter.caldav.CaldavProtocolException: At line 254, column 50: mismatched tag
at org.gege.caldavsyncadapter.caldav.CaldavFacade.parseXML(CaldavFacade.java:452)
at org.gege.caldavsyncadapter.caldav.CaldavFacade.getCalendarsFromSet(CaldavFacade.java:313)
at org.gege.caldavsyncadapter.caldav.CaldavFacade.getCalendarList(CaldavFacade.java:356)
at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.onPerformSync(SyncAdapter.java:124)
... 1 more

**Comment by DavidWiesner** [comment]
This Exception was rethrown from the SaxParser. So in original this was an SaxException, this means that the response from the Server was no valid XML. See [`parseXML()`](https://github.com/gggard/AndroidCaldavSyncAdapater/blob/master/CalDAVSyncAdapter/src/org/gege/caldavsyncadapter/caldav/CaldavFacade.java#L452)

**Comment by gggard** [comment]
@davey69 we should report it in the statistics service
