### ISSUE TITLE
Updating calendar exception java.lang.NullPointerException

### ISSUE THREAD

**Issue by bmbmb** [gggard/AndroidCaldavSyncAdapater#48]
This crashes on a Samsung Galaxy Tab when I try to sync it against owncloud.  It stops with "Unfortunately, CalDAV Sync Adapter has stopped" a few seconds after initiating a sync.  I have version 1.7 installed.

Here is the error log:

```
04-06 01:15:03.889 25721 26184 E SyncAdapter: Updating calendar exception java.lang.NullPointerException
04-06 01:15:03.889 25721 26184 E SyncAdapter: java.lang.NullPointerException
04-06 01:15:03.889 25721 26184 E SyncAdapter:   at android.os.Parcel.readException(Parcel.java:1333)
04-06 01:15:03.889 25721 26184 E SyncAdapter:   at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:182)
04-06 01:15:03.889 25721 26184 E SyncAdapter:   at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:136)
04-06 01:15:03.889 25721 26184 E SyncAdapter:   at android.content.ContentProviderProxy.insert(ContentProviderNative.java:415)
04-06 01:15:03.889 25721 26184 E SyncAdapter:   at android.content.ContentProviderClient.insert(ContentProviderClient.java:66)
04-06 01:15:03.889 25721 26184 E SyncAdapter:   at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.getOrCreateCalendarUri(SyncAdapter.java:335)
04-06 01:15:03.889 25721 26184 E SyncAdapter:   at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.onPerformSync(SyncAdapter.java:129)
04-06 01:15:03.889 25721 26184 E SyncAdapter:   at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:247)
04-06 01:15:03.899 25721 26184 E AndroidRuntime: FATAL EXCEPTION: SyncAdapterThread-1
04-06 01:15:03.899 25721 26184 E AndroidRuntime:    at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.onPerformSync(SyncAdapter.java:149)
04-06 01:15:03.899 25721 26184 E AndroidRuntime:    at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:247)
04-06 01:15:03.899 25721 26184 E AndroidRuntime:    at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.getOrCreateCalendarUri(SyncAdapter.java:335)
04-06 01:15:03.899 25721 26184 E AndroidRuntime:    at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.onPerformSync(SyncAdapter.java:129)
```

**Comment by timoberger** [comment]
this should be fixed within the next release. (or try my developer version 1.8-alpha-2)
feel free to reopen when needed.

**Comment by bmbmb** [comment]
Hi Tim,
I built the current master and tested it on my device, and it looks like it works.
Thanks very much for your efforts.
