### ISSUE TITLE
NPE in AuthenticatorActivity

### ISSUE THREAD

**Issue by gggard** [gggard/AndroidCaldavSyncAdapater#7]
From Google Play :

java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:278)
at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
at java.util.concurrent.FutureTask.run(FutureTask.java:137)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:208)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
at java.lang.Thread.run(Thread.java:864)
Caused by: java.lang.NullPointerException
at org.gege.caldavsyncadapter.authenticator.AuthenticatorActivity$UserLoginTask.doInBackground(AuthenticatorActivity.java:275)
at org.gege.caldavsyncadapter.authenticator.AuthenticatorActivity$UserLoginTask.doInBackground(AuthenticatorActivity.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:264)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
... 5 more

**Comment by gggard** [comment]
Forgot connection refused case
