### ISSUE TITLE
Reccuring events cause CalDAV Sync Adapter to crash

### ISSUE THREAD

**Issue by nodiscc** [gggard/AndroidCaldavSyncAdapater#71]
Hi, I'm forwarding this report from http://f-droid.org/forums/topic/caldav-sync-adapter/ , because I happen to have the same problem.

> Hi,
> I’ve found a way of making a calendar entry which crashes the sync adaptor.
> If you set up an entry which repeats the 4th Monday of every month, starting on 21/1/2013 and repeating until 31/12/2013 it causes a force close when refreshing in the calendar or syncing from Android’s Account menu.
> If you need me to upload the vCal file then just let me know.
> Thanks!

In my own case, trying to sync with a remote calendar that has reccuring events (mine are simple events that repeat daily, during 4 days) causes the app to crash.

Please let me know if you need additional info, thanks.

**Comment by eighthave** [comment]
I am seeing a crash in a recurring event also, sounds like it might be the same issue.  This happened in v1.7 from the Play Store and the latest in git.  Here's the debug log:

```

 23158            SyncAdapter  I  Event /caldav/caldav.php/hans/home/505493d1-b5b4-413d-b881-e6ce9cc23ae1.ics androidUri=content://com.android.calendar/events/832
 23158            SyncAdapter  D  Event compare: "9fdecaaf4e75429de6560f7c64d1464f" <> "9fdecaaf4e75429de6560f7c64d1464f"
 23158            SyncAdapter  I  Event /caldav/caldav.php/hans/home/kh23kjhlkjhwklhahkjashdfkahkjs%40google.com.ics androidUri=null
  2309        ActivityManager  I  Displayed com.android.calendar/.EventInfoActivity: +113ms
 23158           CaldavFacade  D  HttpResponse GET event status=HTTP/1.1 200 OK body= BEGIN:VCALENDAR
 23158           CaldavFacade  D  PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
 23158           CaldavFacade  D  VERSION:2.0
 23158           CaldavFacade  D  BEGIN:VTIMEZONE
 23158           CaldavFacade  D  TZID:America/New_York
 23158           CaldavFacade  D  X-LIC-LOCATION:America/New_York
 23158           CaldavFacade  D  BEGIN:DAYLIGHT
 23158           CaldavFacade  D  TZOFFSETFROM:-0500
 23158           CaldavFacade  D  TZOFFSETTO:-0400
 23158           CaldavFacade  D  TZNAME:EDT
 23158           CaldavFacade  D  DTSTART:19700308T020000
 23158           CaldavFacade  D  RRULE:FREQ=YEARLY;BYDAY=2SU;BYMONTH=3
 23158           CaldavFacade  D  END:DAYLIGHT
 23158           CaldavFacade  D  BEGIN:STANDARD
 23158           CaldavFacade  D  TZOFFSETFROM:-0400
 23158           CaldavFacade  D  TZOFFSETTO:-0500
 23158           CaldavFacade  D  TZNAME:EST
 23158           CaldavFacade  D  DTSTART:19701101T020000
 23158           CaldavFacade  D  RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=11
 23158           CaldavFacade  D  END:STANDARD
 23158           CaldavFacade  D  END:VTIMEZONE
 23158           CaldavFacade  D  BEGIN:VEVENT
 23158           CaldavFacade  D  CREATED:20130718T182144Z
 23158           CaldavFacade  D  LAST-MODIFIED:20130722T150648Z
 23158           CaldavFacade  D  DTSTAMP:20130722T150648Z
 23158           CaldavFacade  D  UID:kh23kjhlkjhwklhahkjashdfkahkjs@google.com
 23158           CaldavFacade  D  RDATE;VALUE=DATE-TIME:20130710T160000Z
 23158           CaldavFacade  D  DTSTART;TZID=America/New_York:20130710T120000
 23158           CaldavFacade  D  X-MOZ-FAKED-MASTER:1
 23158           CaldavFacade  D  X-MOZ-GENERATION:1
 23158           CaldavFacade  D  END:VEVENT
 23158           CaldavFacade  D  BEGIN:VEVENT
 23158           CaldavFacade  D  CREATED:20121228T181639Z
 23158           CaldavFacade  D  LAST-MODIFIED:20130709T195758Z
 23158           CaldavFacade  D  DTSTAMP:20130709T195758Z
 23158           CaldavFacade  D  UID:kh23kjhlkjhwklhahkjashdfkahkjs@google.com
 23158           CaldavFacade  D  SUMMARY:Ae3 Weekly Scrum
 23158           CaldavFacade  D  STATUS:CONFIRMED
 23158           CaldavFacade  D  RECURRENCE-ID;TZID=America/New_York:20130710T120000
 23158           CaldavFacade  D  ORGANIZER;CN=The Guardian Project;SCHEDULE-AGENT=CLIENT:mailto:7nt35ucm3vl
 23158           CaldavFacade  D  5c7rhm2i0jr70ic@group.calendar.google.com
 23158           CaldavFacade  D  ATTENDEE;RSVP=TRUE;CN=abel@guardianproject.info;PARTSTAT=NEEDS-ACTION;CUTY
 23158           CaldavFacade  D  PE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;X-NUM-GUESTS=0:mailto:abel@guardianproj
 23158           CaldavFacade  D  ect.info
 23158           CaldavFacade  D  ATTENDEE;RSVP=TRUE;CN=ifoundfreedom@gmail.com;PARTSTAT=NEEDS-ACTION;CUTYPE
 23158           CaldavFacade  D  =INDIVIDUAL;ROLE=REQ-PARTICIPANT;X-NUM-GUESTS=0:mailto:ifoundfreedom@gmail
 23158           CaldavFacade  D  .com
 23158           CaldavFacade  D  ATTENDEE;RSVP=TRUE;CN=hans@guardianproject.info;PARTSTAT=NEEDS-ACTION;CUTY
 23158           CaldavFacade  D  PE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;X-NUM-GUESTS=0:mailto:hans@guardianproj
 23158           CaldavFacade  D  ect.info
 23158           CaldavFacade  D  ATTENDEE;RSVP=TRUE;CN=lee@rockingtiger.com;PARTSTAT=NEEDS-ACTION;CUTYPE=IN
 23158           CaldavFacade  D  DIVIDUAL;ROLE=REQ-PARTICIPANT;X-NUM-GUESTS=0:mailto:lee@rockingtiger.com
 23158           CaldavFacade  D  ATTENDEE;RSVP=TRUE;CN=cwasser@ninething.org;PARTSTAT=NEEDS-ACTION;CUTYPE=I
 23158           CaldavFacade  D  NDIVIDUAL;ROLE=REQ-PARTICIPANT;X-NUM-GUESTS=0:mailto:cwasser@ninething.org
 23158           CaldavFacade  D  ATTENDEE;RSVP=TRUE;CN=reiter@falljohn.com;PARTSTAT=NEEDS-ACTION;CUTYPE=IND
 23158           CaldavFacade  D  IVIDUAL;ROLE=REQ-PARTICIPANT;X-NUM-GUESTS=0:mailto:poser@falljohn.com
 23158           CaldavFacade  D  ATTENDEE;RSVP=TRUE;CN=Jon Kannfeld;PARTSTAT=NEEDS-ACTION;CUTYPE=INDIVIDUAL
 23158           CaldavFacade  D  ;ROLE=REQ-PARTICIPANT;X-NUM-GUESTS=0:mailto:jonkannfeld@gmail.com
 23158           CaldavFacade  D  ATTENDEE;PARTSTAT=ACCEPTED;ROLE=REQ-PARTICIPANT:mailto:hans@at.or.at
 23158           CaldavFacade  D  DTSTART;TZID=America/New_York:20130710T123000
 23158           CaldavFacade  D  DTEND;TZID=America/New_York:20130710T130000
 23158           CaldavFacade  D  X-GOOGLE-HANGOUT:https://plus.google.com/hangouts/_/calendar/N250MzV1Y20zd
 23158           CaldavFacade  D  mw1YzdyaG0yaTBqckljasdlfkjklajsdkljfW5kYXIuZ29vZ2xlLmNvbQ.thr3ja8gnffr818a
 23158           CaldavFacade  D  5emg1a6alg
 23158           CaldavFacade  D  DESCRIPTION:Weekly scrum. Let's keep it short!\nView your event at http://
 23158           CaldavFacade  D  www.google.com/calendar/event?action=VIEW&eid=dGhyM2phOGduZmZyODE4YTVlbWcx
 23158           CaldavFacade  D  YTZhbGdfMjAxMzA3MTBUMTYwMDAwWiBojjk2h09hKJHASWFucHJvamVjdC5pbmZv&tok=NTIjN
 23158           CaldavFacade  D  250MzV1Y20zdmw1YzdyaG0yaTBqcjcwaWNAZ3JvdXAKHKUHKa8alksd099vZ2xlLmNvbTdlM2J
 23158           CaldavFacade  D  iNjk3NzRiMmNhYmE4ZDkwZDA3ZTAxYjUxNmNlNTFkZjU0Mjk&ctz=America/New_York&hl=e
 23158           CaldavFacade  D  n.
 23158           CaldavFacade  D  X-LIC-ERROR;X-LIC-ERRORTYPE=VALUE-PARSE-ERROR:No value for LOCATION proper
 23158           CaldavFacade  D  ty. Removing entire property:
 23158           CaldavFacade  D  SEQUENCE:2
 23158           CaldavFacade  D  TRANSP:OPAQUE
 23158           CaldavFacade  D  X-MOZ-RECEIVED-SEQUENCE:2
 23158           CaldavFacade  D  X-MOZ-RECEIVED-DTSTAMP:20130709T195214Z
 23158           CaldavFacade  D  END:VEVENT
 23158           CaldavFacade  D  BEGIN:VEVENT
 23158           CaldavFacade  D  CREATED:20121228T181639Z
 23158           CaldavFacade  D  LAST-MODIFIED:20130722T150648Z
 23158           CaldavFacade  D  DTSTAMP:20130722T150648Z
 23158           CaldavFacade  D  UID:kh23kjhlkjhwklhahkjashdfkahkjs@google.com
 23158           CaldavFacade  D  SUMMARY:Ae3 Weekly Scrum
 23158           CaldavFacade  D  STATUS:CONFIRMED
 23158           CaldavFacade  D  RECURRENCE-ID;TZID=America/New_York:20130724T120000
 23158           CaldavFacade  D  ORGANIZER;CN=The Guardian Project;SCHEDULE-AGENT=CLIENT:mailto:7nt35ucm3vl
 23158           CaldavFacade  D  5c7rhm2i0jr70ic@group.calendar.google.com
 23158           CaldavFacade  D  ATTENDEE;RSVP=TRUE;CN=abel@guardianproject.info;PARTSTAT=NEEDS-ACTION;CUTY
 23158           CaldavFacade  D  PE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;X-NUM-GUESTS=0:mailto:abel@guardianproj
 23158           CaldavFacade  D  ect.info
 23158           CaldavFacade  D  ATTENDEE;RSVP=TRUE;CN=ifoundfreedom@gmail.com;PARTSTAT=NEEDS-ACTION;CUTYPE
 23158           CaldavFacade  D  =INDIVIDUAL;ROLE=REQ-PARTICIPANT;X-NUM-GUESTS=0:mailto:ifoundfreedom@gmail
 23158           CaldavFacade  D  .com
 23158           CaldavFacade  D  ATTENDEE;RSVP=TRUE;CN=hans@guardianproject.info;PARTSTAT=NEEDS-ACTION;CUTY
 23158           CaldavFacade  D  PE=INDIVIDUAL;ROLE=REQ-PARTICIPANT;X-NUM-GUESTS=0:mailto:hans@guardianproj
 23158           CaldavFacade  D  ect.info
 23158           CaldavFacade  D  ATTENDEE;RSVP=TRUE;CN=lee@rookingdoggy.com;PARTSTAT=NEEDS-ACTION;CUTYPE=IN
 23158           CaldavFacade  D  DIVIDUAL;ROLE=REQ-PARTICIPANT;X-NUM-GUESTS=0:mailto:lee@rooki
 23158          CalendarEvent  E  Several events in ICS -> only first will be processed
 21289      CalendarProvider2  W  Could not calculate last date.
 21289      CalendarProvider2  W  com.android.calendarcommon2.DateException: Duration.parse(str='PT-16H0M0S') unexpected char '-' at index=2
 21289      CalendarProvider2  W  at com.android.calendarcommon2.Duration.parse(Duration.java:119)
 21289      CalendarProvider2  W  at com.android.providers.calendar.CalendarProvider2.calculateLastDate(CalendarProvider2.java:2862)
 21289      CalendarProvider2  W  at com.android.providers.calendar.CalendarProvider2.updateLastDate(CalendarProvider2.java:2917)
 21289      CalendarProvider2  W  at com.android.providers.calendar.CalendarProvider2.insertInTransaction(CalendarProvider2.java:2114)
 21289      CalendarProvider2  W  at com.android.providers.calendar.SQLiteContentProvider.insert(SQLiteContentProvider.java:96)
 21289      CalendarProvider2  W  at android.content.ContentProvider$Transport.insert(ContentProvider.java:201)
 21289      CalendarProvider2  W  at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:148)
 21289      CalendarProvider2  W  at android.os.Binder.execTransact(Binder.java:351)
 21289      CalendarProvider2  W  at dalvik.system.NativeStart.run(Native Method)
 21289             JavaBinder  E  *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
 21289             JavaBinder  E  java.lang.RuntimeException: Could not insert event.
 21289             JavaBinder  E  at com.android.providers.calendar.CalendarProvider2.insertInTransaction(CalendarProvider2.java:2116)
 21289             JavaBinder  E  at com.android.providers.calendar.SQLiteContentProvider.insert(SQLiteContentProvider.java:96)
 21289             JavaBinder  E  at android.content.ContentProvider$Transport.insert(ContentProvider.java:201)
 21289             JavaBinder  E  at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:148)
 21289             JavaBinder  E  at android.os.Binder.execTransact(Binder.java:351)
 21289             JavaBinder  E  at dalvik.system.NativeStart.run(Native Method)
 23158            SyncAdapter  E  Updating calendar exception java.lang.NullPointerException
 23158            SyncAdapter  E  java.lang.NullPointerException
 23158            SyncAdapter  E  at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.createAndroidEvent(SyncAdapter.java:717)
 23158            SyncAdapter  E  at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.synchroniseEvents(SyncAdapter.java:242)
 23158            SyncAdapter  E  at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.onPerformSync(SyncAdapter.java:138)
 23158            SyncAdapter  E  at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:254)
  2309            SyncManager  D  failed sync operation hans u0 (org.gege.caldavsyncadapter.account), com.android.calendar, SERVER, earliestRunTime 351355397, SyncResult: stats [ numParseExceptions: 3]
  2309            SyncManager  D  not retrying sync operation because the error is a hard error: hans u0 (org.gege.caldavsyncadapter.account), com.android.calendar, SERVER, earliestRunTime 351725171
```

**Comment by eighthave** [comment]
So there seems to be two issues: 
1. there is a bad event, listed in the debug log above. the parsing of it fails.  It turns out that Mozilla Lightning calendar plugin also doesn't parse it correctly.
2. the failed parsing causes a null `Uri` to be returned, and the printing of a log message expects there always to be a `Uri`.  I'm sending a pull request to fix this one.

**Comment by timoberger** [comment]
Hello eighthave,
The event is indeed broken. What is the source of the event?
The null value has already been fixed with commit b788d87f2405f259caf6e8a8da4ae3bbdeff82b3.
I also made some changes based on the broken event.

**Comment by timoberger** [comment]
broken event commit 6ce9e46bccb632574915ca073769e11f78ee4e4a

**Comment by eighthave** [comment]
I can't get this 6ce9e46 commit to pull into master, and its not showing up in the master branch. Is it pushed to a tag or branch?

**Comment by eighthave** [comment]
That event was probably created in the Mozilla Thunderbird calendar plugin called Lightning.  Its probably buggy.

**Comment by timoberger** [comment]
the commit is in my fork at the moment. i will push it to gggard tomorrow.
i am using thunderbird / lightning also. never happend before.

**Comment by timoberger** [comment]
just pushed everything to gggard

**Comment by eighthave** [comment]
thanks, built it and it seems to have fixed my issues.  thanks!

**Comment by Yyuzu** [comment]
Hi,

I'm having the same issue with F-Droid repository's version (1.7 from april 7th). Is there a way to download a nightly build somewhere or update the F-Droid repository ?

Thanks !

**Comment by timoberger** [comment]
as far as i know, f-droids creates new versions based on the tags from github.
i am not the maintainer for this project and i am not going to create new official tags.
but you can test an unofficial release build be me in #86 and give some feedback about it.

**Comment by Yyuzu** [comment]
Ok, but it seems there is only the source code.
I'll try to build it sometime when I'll have time to do so.

**Comment by timoberger** [comment]
i am pretty sure that there was an apk-file...

**Comment by timoberger** [comment]
sorry, i messed around with the release tag earlier this day and must have deleted the attached apk-file.
i restored the file.

**Comment by Yyuzu** [comment]
Thank you, it seems to work now ;-)
I'll come back to you if I encounter crashes or issues.

Thanks
