### ISSUE TITLE
net.fortuna.ical4j.data.ParserException: Error at line 23:Cannot set timezone for UTC properties

### ISSUE THREAD

**Issue by eighthave** [gggard/AndroidCaldavSyncAdapater#85]
I have two events that are causing this exception.  I'm running the current head from git. 

Here is the first event and the backtrace:

```
 23158            SyncAdapter  D  Event compare: "2329176c1c3b821be57b52bece97dc7f" <> "2329176c1c3b821be57b52bece97dc7f"
 23158            SyncAdapter  I  Event /caldav/caldav.php/hans/home/81ae8242-93e1-48a5-b47d-4e09f5f89c10.ics androidUri=null
 23158           CaldavFacade  D  HttpResponse GET event status=HTTP/1.1 200 OK body= BEGIN:VCALENDAR
 23158           CaldavFacade  D  PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
 23158           CaldavFacade  D  VERSION:2.0
 23158           CaldavFacade  D  BEGIN:VTIMEZONE
 23158           CaldavFacade  D  TZID:America/New_York
 23158           CaldavFacade  D  X-LIC-LOCATION:America/New_York
 23158           CaldavFacade  D  BEGIN:DAYLIGHT
 23158           CaldavFacade  D  TZOFFSETFROM:-0500
 23158           CaldavFacade  D  TZOFFSETTO:-0400
 23158           CaldavFacade  D  TZNAME:EDT
 23158           CaldavFacade  D  DTSTART:19700308T020000
 23158           CaldavFacade  D  RRULE:FREQ=YEARLY;BYDAY=2SU;BYMONTH=3
 23158           CaldavFacade  D  END:DAYLIGHT
 23158           CaldavFacade  D  BEGIN:STANDARD
 23158           CaldavFacade  D  TZOFFSETFROM:-0400
 23158           CaldavFacade  D  TZOFFSETTO:-0500
 23158           CaldavFacade  D  TZNAME:EST
 23158           CaldavFacade  D  DTSTART:19701101T020000
 23158           CaldavFacade  D  RRULE:FREQ=YEARLY;BYDAY=1SU;BYMONTH=11
 23158           CaldavFacade  D  END:STANDARD
 23158           CaldavFacade  D  END:VTIMEZONE
 23158           CaldavFacade  D  BEGIN:VEVENT
 23158           CaldavFacade  D  CREATED;TZID=America/New_York:20130129T140250
 23158           CaldavFacade  D  LAST-MODIFIED:20130131T183734Z
 23158           CaldavFacade  D  DTSTAMP:20130131T183734Z
 23158           CaldavFacade  D  UID:81ae8242-93e1-48a5-b47d-4e09f5f89c10
 23158           CaldavFacade  D  SUMMARY:Hans interview with Fred
 23158           CaldavFacade  D  STATUS:CONFIRMED
 23158           CaldavFacade  D  ORGANIZER;RSVP=FALSE;CN=The Guardian Project;CUTYPE=INDIVIDUAL:mailto:7nt3
 23158           CaldavFacade  D  891lkjdfcjla834asr70ic@group.calendar.google.com
 23158           CaldavFacade  D  DTSTART;TZID=America/New_York:20130206T150000
 23158           CaldavFacade  D  DTEND;TZID=America/New_York:20130206T160000
 23158           CaldavFacade  D  SEQUENCE:0
 23158           CaldavFacade  D  X-GOOGLE-EDITURL:https://www.google.com/calendar/feeds/9asdfsdfkjdfc7rhm2i
 23158           CaldavFacade  D  0jr70ic%40group.calendar.google.com/private/full/rhb2faj87jbm4v3m7itl18i46
 23158           CaldavFacade  D  c/63495169370
 23158           CaldavFacade  D  URL:https://www.google.com/calendar/event?eid=cmhiMmZhajg3amJtNHYzbTdpdGwx
 23158           CaldavFacade  D  OGk0NmMgN250Mzjla834asw1YzdyaG0yaTBqcjcwaWNAZw
 23158           CaldavFacade  D  TRANSP:OPAQUE
 23158           CaldavFacade  D  CLASS:DEFAULT
 23158           CaldavFacade  D  END:VEVENT
 23158           CaldavFacade  D  END:VCALENDAR
 23158            SyncAdapter  E  Parser exception
 23158            SyncAdapter  E  net.fortuna.ical4j.data.ParserException: Error at line 23:Cannot set timezone for UTC properties
 23158            SyncAdapter  E  at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:148)
 23158            SyncAdapter  E  at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:210)
 23158            SyncAdapter  E  at net.fortuna.ical4j.data.CalendarBuilder.build(CalendarBuilder.java:191)
 23158            SyncAdapter  E  at org.gege.caldavsyncadapter.caldav.entities.CalendarEvent.parseIcs(CalendarEvent.java:701)
 23158            SyncAdapter  E  at org.gege.caldavsyncadapter.caldav.entities.CalendarEvent.fetchBody(CalendarEvent.java:186)
 23158            SyncAdapter  E  at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.createAndroidEvent(SyncAdapter.java:705)
 23158            SyncAdapter  E  at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.synchroniseEvents(SyncAdapter.java:242)
 23158            SyncAdapter  E  at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.onPerformSync(SyncAdapter.java:138)
 23158            SyncAdapter  E  at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:254)
 23158            SyncAdapter  E  Caused by: java.lang.UnsupportedOperationException: Cannot set timezone for UTC properties
 23158            SyncAdapter  E  at net.fortuna.ical4j.model.property.UtcProperty.setTimeZone(UtcProperty.java:98)
 23158            SyncAdapter  E  at net.fortuna.ical4j.data.CalendarBuilder.updateTimeZone(CalendarBuilder.java:372)
 23158            SyncAdapter  E  at net.fortuna.ical4j.data.CalendarBuilder.access$3(CalendarBuilder.java:370)
 23158            SyncAdapter  E  at net.fortuna.ical4j.data.CalendarBuilder$ContentHandlerImpl.parameter(CalendarBuilder.java:296)
 23158            SyncAdapter  E  at net.fortuna.ical4j.data.CalendarParserImpl$ParameterParser.parse(CalendarParserImpl.java:342)
 23158            SyncAdapter  E  at net.fortuna.ical4j.data.CalendarParserImpl$ParameterParser.access$1(CalendarParserImpl.java:297)
 23158            SyncAdapter  E  at net.fortuna.ical4j.data.CalendarParserImpl$ParameterListParser.parse(CalendarParserImpl.java:283)
 23158            SyncAdapter  E  at net.fortuna.ical4j.data.CalendarParserImpl$PropertyParser.parse(CalendarParserImpl.java:213)
 23158            SyncAdapter  E  at net.fortuna.ical4j.data.CalendarParserImpl$PropertyParser.access$1(CalendarParserImpl.java:200)
 23158            SyncAdapter  E  at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:178)
 23158            SyncAdapter  E  at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.parse(CalendarParserImpl.java:396)
 23158            SyncAdapter  E  at net.fortuna.ical4j.data.CalendarParserImpl$ComponentParser.access$1(CalendarParserImpl.java:382)
 23158            SyncAdapter  E  at net.fortuna.ical4j.data.CalendarParserImpl$PropertyListParser.parse(CalendarParserImpl.java:175)
 23158            SyncAdapter  E  at net.fortuna.ical4j.data.CalendarParserImpl.parse(CalendarParserImpl.java:125)
 23158            SyncAdapter  E  ... 8 more
```

 I then updated ical4j to the latest in the `ical4j-1.x-maintenance` branch, and got this backtrace:

```
 10283         AndroidRuntime  E  FATAL EXCEPTION: SyncAdapterThread-2
 10283         AndroidRuntime  E  java.lang.ExceptionInInitializerError
 10283         AndroidRuntime  E  at net.fortuna.ical4j.model.DefaultTimeZoneRegistryFactory.createRegistry(DefaultTimeZoneRegistryFactory.java:48)
 10283         AndroidRuntime  E  at net.fortuna.ical4j.data.CalendarBuilder.<init>(CalendarBuilder.java:123)
 10283         AndroidRuntime  E  at org.gege.caldavsyncadapter.caldav.entities.CalendarEvent.parseIcs(CalendarEvent.java:694)
 10283         AndroidRuntime  E  at org.gege.caldavsyncadapter.caldav.entities.CalendarEvent.fetchBody(CalendarEvent.java:186)
 10283         AndroidRuntime  E  at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.createAndroidEvent(SyncAdapter.java:705)
 10283         AndroidRuntime  E  at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.synchroniseEvents(SyncAdapter.java:242)
 10283         AndroidRuntime  E  at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.onPerformSync(SyncAdapter.java:138)
 10283         AndroidRuntime  E  at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:254)
 10283         AndroidRuntime  E  Caused by: java.lang.NullPointerException
 10283         AndroidRuntime  E  at net.fortuna.ical4j.util.ResourceLoader.getResourceAsStream(ResourceLoader.java:77)
 10283         AndroidRuntime  E  at net.fortuna.ical4j.model.TimeZoneRegistryImpl.<clinit>(TimeZoneRegistryImpl.java:76)
 10283         AndroidRuntime  E  ... 8 more
```

**Comment by timoberger** [comment]
this kills ical4j
CREATED;TZID=America/New_York:20130129T140250

**Comment by timoberger** [comment]
workaround in 4aa970b6c6c1b31c7bff9fc19243b6f2a755eac3

**Comment by eighthave** [comment]
Looks like this commit is also not in master.  Maybe try a `git push origin master`.  Otherwise the newest commits are probably not in the master branch in your local repo.
